POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1iIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QucnUiLCJleHAiOjE3NDA2MDMxOTYsInVzZXJJZCI6MX0.SqHIlovOvjTIdPH_BTShHXCGqNrWWTCR1Nazr1pmjX0